n : 2000
d: 20
s0: 120 # following dagma, better be 4 * d
graph_type : ER
sem_type : gauss
est_type : tau+ # [tau, tau+]
fdr : 0.2
device : 7
numeric: False # let values < numeric_precision be 0.
numeric_precision : 1e-1
device : cuda:7
root_path: simulated_data

# True: t_list = concat([0], sort.unique.abs(Z))
# False: t_list = sort.concat([0], unique(Z))
# change little, should be True as
## negatives of Z will affect denorminator
abs_t_list : True

# True : mask = (np.abs(Z) >= t_last)
# False : mask = (Z >= t_last)
# change little, should be False
## negative parts are usually too small (< selected threshold)
abs_selection : False

# dag_1: first remove Z from min to max, until dag, then fdr control filter
# dag_2: first include Z from max to min, until not dag, then fdr control filter

# dag_3: first compute fdr control z and q-value matrix Q, then remove Z from min to max until dag.
## it's obvious max(dag(Z), fdr(Z)) will be chosen. 
## if dag_control is excuted only when fdr(Z)-filtered graph is not dag, the dag(Z) must be chosen.
# dag_4: first compute fdr control z and q-value matrix Q, then include Z from max to min until not dag.

# dag_5: first compute fdr control z and q-value matrix Q, then remove Q from max to min until dag.
## in this case, no selected threshold.
# dag_6: first compute fdr control z and q-value matrix Q, then include Q from min to max until not dag.

# dag_7L first remove W from min to max, until dag, then fdr control filter
dag_control : None

# control_type
## type_3_control: column-wise model-x 
## type_3_control_global: global model-x
## type_4_control: column-wise model-x + dag_control
## type_4_control: global model-x + dag_control
### if dag_control == None, type_4_control(_global) == type_3_control(_global)

##############################
# knockoffGAN parameters
##############################

niter: 2000
norm: False

##################################
# network deconvolution parameters 
# used before fdr control
# used on learned W 
# (after dagma fitting)
##################################

deconv: False
beta: 0.9 # valid only when deconv is True